### ISSUE TITLE
this doesn't work

### ISSUE THREAD

**Issue by georgettica** [mgred/asciidoctor-action#1]
might want to look into 
https://gist.github.com/StephenKing/d74cddcbd1eab3529a678b1ca6fad530

I used it and it worked as expected.

see code in https://github.com/georgettica/contact-fixer/pull/8

**Comment by mgred** [comment]
@georgettica you use  [`avattathil/asciidoctor-action`](https://github.com/avattathil/asciidoctor-action). Try `mgred/asciidoctor-action` instead :wink:

**Comment by georgettica** [comment]
I did, and it didn't work!

The issue was that the README.adoc file was not detected..

Some of your forks changed the command to be `eval` which solved my issue but it's still doesn't feel right.

I would be glad to work with you on it

**Comment by mgred** [comment]
@georgettica ok, lets do it. I will have a look this evening. Do you have any suggestions already?

**Comment by georgettica** [comment]
So it comes down to the action file we use.

I think it doesn't pass the arguments correctly.

I will create now a PR to use your check in.addition to mine and we can experiment there

**Comment by georgettica** [comment]
Here it is, should fail the action

And the other file does work, the PR I sent b4 had a copout of using an alternative, but in the commits you can see I struggled to make it work

https://github.com/georgettica/contact-fixer/pull/12

**Comment by mgred** [comment]
@georgettica Sorry for my late response and thanks for you detailed feedback!
I updated `master` to use `exec` with the given argument inside the container. This seems to be best practice when running commands in `entrypoint.sh`. Can you try this version?

**Comment by georgettica** [comment]
Sure! I wasn't sure exec was the right way to go, will change now the PR

**Comment by georgettica** [comment]
And what about the change to checkout v2?

**Comment by mgred** [comment]
> And what about the change to checkout v2?

You mean to be able to distinct the version like `mgred/asciidoctor-action@v2`?

I think there is no need to change/bump the version since the action works the same way as before, no breaking change here.

**Comment by mgred** [comment]
@georgettica I saw in you workflow that it still failed. This is because the `args` are passed in as quoted to the `docker run` command. See https://github.com/georgettica/contact-fixer/runs/1691430707#step:4:4

I changed the `entrypoint.sh` again to use unquoted arguments with the `exec` command.

**Comment by georgettica** [comment]
Trying again

**Comment by georgettica** [comment]
Yay! Now it works!
